Configure support for arm64

diff --git a/package/scripts/common/quarto b/package/scripts/common/quarto
--- a/package/scripts/common/quarto
+++ b/package/scripts/common/quarto
@@ -135,10 +135,19 @@ if [ "$QUARTO_DENO" == "" ]; then
       echo "quarto script failed: unrecognized architecture " ${FULLARCH}
       exit 1
     fi
-    export QUARTO_DENO="${SCRIPT_PATH}/tools/${DENO_DIR}/deno"
+
   else
-    export QUARTO_DENO="${SCRIPT_PATH}/tools/deno"
+    NIXARCH=$(uname -m)
+    if [[ $NIXARCH == "x86_64" ]]; then
+      DENO_DIR=deno-x86_64-unknown-linux-gnu
+    elif [[ $NIXARCH == "aarch64" ]]; then
+      DENO_DIR=deno-aarch64-unknown-linux-gnu
+    else
+      echo "configure script failed: unrecognized architecture " ${NIXARCH}
+      exit 1
+    fi
   fi
+  export QUARTO_DENO="${SCRIPT_PATH}/tools/${DENO_DIR}/deno"
 
 fi
 
