download both architectures and use the correct one on macOS

diff --git a/package/scripts/common/quarto b/package/scripts/common/quarto
--- a/package/scripts/common/quarto
+++ b/package/scripts/common/quarto
@@ -19,6 +19,8 @@ else
   SCRIPT_PATH="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
 fi
 
+source ${SCRIPT_PATH}/../../scripts/common/utils.sh
+
 # Check if we are running 'Dev Mode' and if so, override values for devs
 SCRIPT_BASENAME=$(basename $SCRIPT_PATH)
 if [ "${SCRIPT_BASENAME}" == "bin" ]; then
@@ -119,7 +121,22 @@ else
 fi
 
 if [ "$QUARTO_DENO" == "" ]; then
-  export QUARTO_DENO="${SCRIPT_PATH}/tools/deno"
+
+  if [[ $OSTYPE == 'darwin'* ]]; then
+    FULLARCH=$(uname -sm)
+    
+    if [[ $FULLARCH == "Darwin x86_64" ]]; then
+      DENO_DIR=deno-x86_64-apple-darwin
+    elif [[ $FULLARCH == "Darwin arm64" ]]; then
+      DENO_DIR=deno-aarch64-apple-darwin
+    else
+      echo "quarto script failed: unrecognized architecture " ${FULLARCH}
+      exit 1
+    fi
+  else
+    DENO_DIR=deno-x86_64-unknown-linux-gnu
+  fi
+  export QUARTO_DENO="${SCRIPT_PATH}/tools/${DENO_DIR}/deno"
 fi
 
 # Be sure to include any already defined QUARTO_DENO_OPTIONS
