Feature/deno 1.25.1 (#2270)
* conf update

* deno dom comment

* deno dom comment

* partial work to deno v1.25

* update to latest deno-dom:

* fix import maps as generated by v1.25.0

* add rust_backtrace to narrow error in CI

* add rust_backtrace=full to narrow error in CI

* use canary commit

* use stdlib 0.153.0

* use artifcats in deno_dom configuration

* 1.25.1

* download both architectures and use the correct one on macOS

* update quarto and tests scripts

* make symlink for the current architecture so that VS code finds deno

* build artifacts

* changelog

* changelog

* update rust launcher

* address code review comments

Co-authored-by: JJ Allaire <jj@rstudio.com>

diff --git a/package/scripts/common/quarto b/package/scripts/common/quarto
--- a/package/scripts/common/quarto
+++ b/package/scripts/common/quarto
@@ -119,7 +119,21 @@ else
 fi
 
 if [ "$QUARTO_DENO" == "" ]; then
-  export QUARTO_DENO="${SCRIPT_PATH}/tools/deno"
+  if [[ $OSTYPE == 'darwin'* ]]; then
+    FULLARCH=$(uname -sm)
+    
+    if [[ $FULLARCH == "Darwin x86_64" ]]; then
+      DENO_DIR=deno-x86_64-apple-darwin
+    elif [[ $FULLARCH == "Darwin arm64" ]]; then
+      DENO_DIR=deno-aarch64-apple-darwin
+    else
+      echo "quarto script failed: unrecognized architecture " ${FULLARCH}
+      exit 1
+    fi
+  else
+    DENO_DIR=deno-x86_64-unknown-linux-gnu
+  fi
+  export QUARTO_DENO="${SCRIPT_PATH}/tools/${DENO_DIR}/deno"
 fi
 
 # Be sure to include any already defined QUARTO_DENO_OPTIONS
