Add some error message to understand what is happening

diff --git a/.github/workflows/test-smokes.yml b/.github/workflows/test-smokes.yml
--- a/.github/workflows/test-smokes.yml
+++ b/.github/workflows/test-smokes.yml
@@ -172,9 +172,9 @@ jobs:
             echo ">>> ./run-tests.sh ${file}"
             ./run-tests.sh $file
             status=$?
-            [ $status -eq 0 ] && echo "No error in this test file" || haserror=1
+            [ $status -eq 0 ] && echo ">>> No error in this test file" || haserror=1
           done
-          [ $haserror -eq 0 ] && echo "All tests passed" || exit 1
+          [ $haserror -eq 0 ] && echo ">>> All tests passed" || exit 1
         working-directory: tests
         shell: bash
 
@@ -190,13 +190,16 @@ jobs:
             ./run-tests.ps1 $file
             $status=$LASTEXITCODE
             if ($status -eq 1) {
+              Write-Host ">>> Error found in test file"
               $haserror=$true
-            } 
+            } else {
+              Write-Host ">>> No error in this test file"
+            }
           }
           if ($haserror) {
             Exit 1
           } else {
-            Write-Host "All tests have passed"
+            Write-Host ">>> All tests have passed"
           }
         working-directory: tests
         shell: pwsh
